FROM php:7-fpm

RUN pecl install xdebug-2.8.1 \
    && docker-php-ext-enable xdebug

RUN apt-get update && apt-get install \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
